### ISSUE TITLE
Make it possible to configure "Globals" and "Profiles" directly from within the values.yaml

### ISSUE THREAD

**Issue by philipsens** [ibissource/zaakbrug#23]
Now the user has to make his own configMap with the data for Globals.json and Profiles.json.

That wouldn't be the case if we create a configMap within the chart. This is possible by doing something like:
```tpl
{{ include "my_tpl" . | fromYaml | toJson }}
```
Then the user can add all info to the values instead of creating a json and putting it into a configMap.

Example: 
```json
{
    "organizations": [
		{
			"gemeenteNaam": "Haarlem",
			"gemeenteCode": "0392",
			"RSIN": "001005650"
		}
	],
    "rolMapping": {
        "heeftBetrekkingOp": "BetrekkingOp",
        "heeftAlsBelanghebbende": "Belanghebbende",
        "heeftAlsInitiator": "Initiator",
        "heeftAlsUitvoerende": "Uitvoerende",
        "heeftAlsVerantwoordelijke": "Verantwoordelijke",
        "heeftAlsGemachtigde": "Gemachtigde",
        "heeftAlsOverigBetrokkene": "OverigeBetrokkene"
    }
}
```
Would change to:
```yaml
      globalsConfigMap:
        organizations:
          - gemeenteNaam: "Haarlem"
            gemeenteCode: "0392"
            RSIN: "001005650"
        rolMapping:
          heeftBetrekkingOp: "BetrekkingOp",
          heeftAlsBelanghebbende: "Belanghebbende",
          heeftAlsInitiator: "Initiator",
          heeftAlsUitvoerende: "Uitvoerende",
          heeftAlsVerantwoordelijke: "Verantwoordelijke",
          heeftAlsGemachtigde: "Gemachtigde",
          heeftAlsOverigBetrokkene: "OverigeBetrokkene"
```
